config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  root "posts#index"

  devise_for :users

  resources :posts do

    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true

  def self.sort_created
    order('created_at DESC')
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    #check that this is the connection between the @post_id
    @comment.post = @post
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        CommentsMailer.notify_post_owner(@comment).deliver_later
        format.html { redirect_to post_path(@post), notice: "Comment Created!" }
        format.js { render }
      else
        #clarify this render: as we are in the comments controller...
        format.html { render 'posts/show' }
        format.js { render }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: "Comment Deleted" }
      format.js { render }
    end
  end

  def edit
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
  end

  def update
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    respond_to do |format|
      if @comment.update params.require(:comment).permit(:body)
        format.html { redirect_to @post, notice: "Comment updated" }
        format.js { render :update_success }
      else
        format.html { render :edit }
        format.js { render :update_failure }
      end
    end

  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div id="<%= dom_id(c) %>">
  <p><%= c.body %></p><br>
  <div class="comment-create">
    <p>Created : <%= time_ago_in_words(c.created_at) %> ago</p>
    <p>Created by: <%= c.user.full_name %></p>
  </div>
  <div class="comment-change">
    <% if user_signed_in? && current_user.id == c.user.id %>
      <%= link_to "Delete Comment | ", post_comment_path(@post, c), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete this comment?"}, class: "fa fa-trash-o fa-lg" %>
    <!-- using bootstrap modal -->
      <%= link_to "edit", edit_post_comment_path(@post, c), remote: true, class: "", data: { toggle: "modal", target: "#edit-comment-modal" }, class: "fa fa-pencil fa-lg" %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= simple_form_for @comment, url: [@post, @comment], remote: true, html: {class: "form-horizontal"} do |c| %>
    <%= c.input :body, label: false, placeholder: "Add your comments here", class: "form-control", :input_html => {:rows => 8} %>
    <%= c.submit "Submit", class: "btn btn-warning" %>
  <% end %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  $(".comment_form").html("<%= j render "/comments/form" %>");
<% else %>
  $(".comments").prepend("<%= j render partial: "/comments/comments", locals: {c: @comment} %>");
  $("#comment_body").val("");

  <% @comment = Comment.new %>
  $(".comment_form").html("<%= j render "/comments/form" %>");

<% end %>

app/views/comments/destroy.js.erb
// get the id from the inspector
$("#<%= dom_id(@comment) %>").fadeOut();

app/views/comments/edit.js.erb
$(".modal-body").html('<%= j render partial: "/comments/form" %>')

app/views/comments/update_failure.js.erb
$(".modal-body").html('<%= j render partial: "/comments/form" %>')

app/views/comments/update_success.js.erb
$("#edit-comment-modal").modal("hide");
$("#<%= dom_id(@comment) %>").replaceWith("<%= j render partial: "/comments/comments", locals: {c: @comment} %>");