config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  root "posts#index"

  devise_for :users

  resources :posts do

    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find params[:post_id]
    like = current_user.likes.new
    like.post = @post
    respond_to do |format|
      if like.save
        format.html { redirect_to post, notice: "Liked!" }
        format.js { render }
      else
        format.html { redirect_to post, alert: "Like not working, try again!" }
        format.js { render }
      end
    end
  end

  def destroy
    like = current_user.likes.find params[:id]
    @post = like.post
    # @post = Post.find params[:post_id]
    like.destroy
    respond_to do |format|
      format.html { redirect_to like.post, notice: "Unliked :(" }
      format.js { render }
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% like = @post.likes.find_by_user_id(current_user.id) if user_signed_in? %>
<% if like %>
  <%= link_to fa_icon("thumbs-up 4x"), post_like_path(@post, like), method: :delete, remote: true %>
<% else %>
  <%= link_to fa_icon("thumbs-o-up 4x"), post_likes_path(@post), method: :post, remote: true %>
<% end %>

app/views/likes/create.js.erb
$('.like').html("<%= j render "/likes/like" %>");

app/views/likes/destroy.js.erb
$('.like').html("<%= j render "/likes/like" %>");