config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  root "posts#index"

  devise_for :users

  resources :posts do

    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  acts_as_taggable

  has_many :favourites, dependent: :destroy
  has_many :users_who_favourite, through: :favourites, source: :user

  after_initialize :default_count

  mount_uploader :image, ImageUploader

  def self.search_for(find)
    where("title ILIKE ? OR body ILIKE ?", "%#{find}%", "%#{find}%")
  end

  def self.sort_created
    order('created_at DESC')
  end

  def self.recent_five
    order("created_at DESC").limit(5)
  end

  def self.most_viewed_post
    order("view_count DESC").first
  end

  def increment_view_count
    increment!(:view_count)
  end

  def default_count
    view_count ||= 0
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search]
      # render text: params
      @posts = Post.search_for(params[:search]).sort_created.page(params[:page]).per(6)
    elsif params[:tag]
      @posts = Post.tagged_with(params[:tag]).sort_created.page(params[:page]).per(6)
    else
      @posts = Post.all.sort_created.page(params[:page]).per(6)
    end
    @post_viewed = Post.most_viewed_post
    @posts_recent = Post.recent_five
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.user = current_user
    # or can be written in one line
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
    @post.increment_view_count
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      flash[:notice] = "Could not Update!"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end


private

  def find_post
    @post = Post.find params[:id]
    redirect_to root_path, alert: "Access Denied" unless can? :manage, @post
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :tag_list)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="new-post-form">
  <%= simple_form_for @post do |p| %>
      <%= p.input :title, label: "Blog Title", placeholder: "Add blog title here" %>
      <%= p.input :body, label: "Blog Content", placeholder: "Add your insightful blog here, can be written in markdown!", input_html: {:rows => 12}  %>
      <%= p.input :image, class: "form-control" %>
      <%= p.input :tag_list, placeholder: "Tags (separated by commas)" %>
      <%= p.button :submit, :class => "btn btn-info" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="new-post">
    <h1>Edit Post</h1>
    <%= render "form" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid main-content">
  <!-- This is for the alert notices at the top of the page -->
  <% if flash[:notice] %>
    <p class="alert alert-success"><%= notice %></p>
  <% elsif flash[:alert] %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<!-- This is for the most viewed post -->
  <div class="col-sm-12 viewed-recent">
    <div class="container">
      <div class="col-xs-12 col-sm-7 mini-search">
        <div class="search-container col-sm-5 col-md-8 col-offset-md-3">
          <%= form_tag("/", method: "get") do %>
            <p><%#= label_tag(:search, "Search the Blog Posts : ") %></p>
            <p><%= text_field_tag :search, nil, placeholder: "Enter a blog post to search", class: "form-control input-md search-box" %></p>
            <%= submit_tag "Search", :class => "btn btn-info search-submit" %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-7">
        <div class="most_viewed">
          <div class="image-wrapper">
            <%= image_tag @post_viewed.image.url(:large), class: "image" %>
          </div>
          <div class="most-viewed-post">
            <h4>MOST VIEWED POST</h4>
            <h2><%= link_to @post_viewed.title, post_path(@post_viewed) %></h2>
            <div id="post-body">
              <%= raw markdown.render(@post_viewed.body.truncate(600, omission: '...(continued)')) %>
            </div>
          </div>
        </div>
      </div>

<!-- this is the 5 most recent posts -->
      <div class="col-sm-5 col-xs-12 post-tags">
        <h3>Search posts by tags</h3>
        <div id="tag_cloud">
          <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
          <p class="fa fa-tag"> <%= link_to tag.name, tag_path(tag.name), class: css_class %></p>
          <% end %>
        </div>
      </div>

      <div class="col-sm-5 col-xs-12">
        <div class="recent-posts">
          <h4>RECENT POSTS</h4>
          <ul>
            <% @posts_recent.each do |r| %>
            <li>
              <h3 class="post-header"><%= link_to r.title, post_path(r) %></h3>
              <div id="post-body-recent">
                <%= raw markdown.render(r.body.truncate(100)) %>
              </div>
              <div class="created-text">
                <% if r.user present? %>
                  <p>Created By: <%= r.user.full_name %></p>
                  <p><%= r.created_at.strftime("%B, %d, %Y") %></p>
                <% end %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

<!-- This is the main content that is being iterated over -->
  <div class="container">
    <% @posts.each do |p| %>
      <div class="col-md-4 col-xs-12 col-sm-6 outer-container">
        <div class="show_posts">
          <div class="image-wrapper">
            <% if p.image.present? %>
              <%= image_tag p.image.url(:medium), class: "medium-image" %>
            <% end %>
          </div>
          <div class="post-content">
            <h2><%= link_to p.title.truncate(50), post_path(p) %></h2>
            <div id="post-body-each">
              <%= raw markdown.render(p.body.truncate(150, omission: '...(continued)')) %>
            </div>
            <div class="created-text">
              <% if p.user present? %>
                <p>Created By: <%= p.user.full_name %></p>
                <p><%= p.created_at.strftime("%B, %d, %Y") %></p>
              <% end %>
            </div>
            <div class="like-buttons">
              <% if p.likes.count > 1 %>
                <p>Likes: <%= p.likes.count %></p>
              <% else %>
                <p>Like: <%= p.likes.count %></p>
              <% end %>
            </div>
          </div>
            <div class="social-buttons">
              <%= social_share_button_tag(p.title, :popup => "true") %>
            </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- kaminari -->
  <div class="container">
    <%= paginate @posts, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="new-post">
  <h1>Add a new post </h1>
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:large), class: "post-image" %>
<div class="container content-padding">
  <div class="show-post-content">
    <div class="col-sm-10">
      <h1 class="post-title"><%= @post.title %></h1>
    </div>
    <div class="col-sm-2">
      <div class="likes-and-favs">
        <% if user_signed_in? %>
        <!-- render the partial favourite -->
          <div class="favourite">
            <%= render partial: "/favourites/favourite" %>
          </div>
        <!-- render the like partial -->
          <div class="like">
            <%= render partial: "/likes/like" %>
          </div>
          <% else %>
          <!-- to take up the space when the like and favourite buttons are not there. -->
          <div class="hidden-div">
            <div class="favourite">
              <%= render partial: "/favourites/favourite" %>
            </div>
          <!-- render the like partial -->
            <div class="like">
              <%= render partial: "/likes/like" %>
          </div>
        </div>
      <% end %>
      </div>
      </br>
    </div>

    <p>Submitted <%= time_ago_in_words(@post.created_at) %> ago</p>
    <div id="post-body">
      <%= raw markdown.render(@post.body) %></br>
    </div>
    <p>Created By: <%= @post.user.full_name %></p>

    <div class="edit-buttons">
      <% if user_signed_in? %>
        <% if can? :edit, @post %>
          <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-default" %> |
        <% end %>
        <% if can? :destroy, @post %>
          <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>

    <div id="tag_cloud2">
      <h4>Tags</h4>
      <% tag_cloud @post.tag_counts, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>
  <!-- Social Buttons -->
    <div class="social-buttons">
      <%= social_share_button_tag(@post.title, :popup => "true") %>
    </div>
  </div>

<!-- Comment form -->
  <div class="col-sm-12 outside-comment-form">
    <div class="comment_form col-sm-8">
      <%= render partial: "comments/form" %>
    </div>
  </div>

  <div class="all-comments">
    <h1>Comments</h1>
    <p>There are <%= @post.comments.count %> Comments</p>
    <span>Login to add your own</span>
    <!-- this is a shorthand for the partial -->
    <%#= render @post.comments %>
    <% @post.comments.sort_created.each do |comment| %>
      <div class="comments">
        <div class="each-comment">
          <%= render partial: "comments/comments", locals: { c: comment} %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- What should this paginate???? -->
  <%#= paginate @post.comments %>

  <!-- Modal -->
  <div class="modal fade" id="edit-comment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Edit Comments</h4>
        </div>
        <div class="modal-body">
          ...
        </div>
      </div>
    </div>
  </div>

</div>