config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
  end

  root "posts#index"

  devise_for :users

  resources :posts do

    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]

  end

  resources :favourites, only: [:index]

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lobster' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Cabin' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BloggAz", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><h3>Welcome <%= current_user.full_name %></h3><li>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Favourites", favourites_path, class: "" %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "" %></li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path, class: "" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<%= yield %>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lobster' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,100' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BlogAz", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <i class="fa fa-search fa-2x search-btn"></i>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><h3>Welcome <%= current_user.full_name %></h3><li>
            <li><%= link_to "New Post", new_post_path %></li>
            <li><%= link_to "Favourites", favourites_path, class: "" %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "" %></li>
          <% else %>
            <li><%= link_to "Register", new_user_registration_path, class: "" %></li>
            <li><%= link_to "Sign In", new_user_session_path, class: "" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>


<!-- Jumbotron for the search fields and the background picture -->
<div class="jumbotron container">
  <div class="jumbo-container container">
    <p>THE</p>
    <div class="jumbo-title">
      <h1>Blog</h1>
    </div>
  </div>
</div>



<%= yield %>


<!-- Sidebar links -->
  <!-- <div class="container-fluid full-site"> -->
      <!-- <div class="col-sm-2 sidebar">
        <ul>
          <li class="sidebar_blog">
            <% if current_page?(root_path) %>
              All Blogs
            <% else %>
              <%= link_to "All Blog Posts", root_path %>
            <% end %>
          </li>
        </ul> -->


<!-- Content links -->
      <!-- <ul>
        <li class"sidebar_social">Social</li>
        <li><a href="http://twitter.com/azhopkins">Twitter</a></li>
        <li><a href="http://github.com/azrielh">GitHub</a></li>
        <li><a href="mailto:azhopkins@gmail.com">Email</a></li>
      </ul>
    </div> -->

    <!-- from devise -->



</body>
</html>